### ISSUE TITLE
Fix migrations

### ISSUE THREAD

**Issue by jacobwegner** [eldarion/formly#19]
Formly is missing a migration out of the box; we need to add that migration and also set up tests to verify migrations are working as expected going forward.

**Comment by gregnewman** [comment]
@jacobwegner this commit adds the missing migration.

**Comment by jacobwegner** [comment]
Found another missing migration in 1676598; want to get automated tests on this prior to next release.

**Comment by grahamu** [comment]
@jacobwegner this should be resolved by #33.

**Comment by grahamu** [comment]
resolved by #33
