### ISSUE TITLE
Update django-jsonfield dependency for compatibility with Django 1.7

### ISSUE THREAD

**Issue by jacobwegner** [eldarion/formly#6]
django-jsonfield 0.8.10 relies on django.utils.simplejson, which was deprecated in Django 1.5 and removed in Django 1.7

**Comment by jtauber** [comment]
@jacobwegner Is the fix just upgrading django-jsonfield or do we need to switch to something else?

**Comment by jacobwegner** [comment]
Fixed in `0.6` release.

**Comment by ronnix** [comment]
Note that the installation docs still mention the old version.

**Comment by ronnix** [comment]
I opened a pull request (#7) for this issue.
